// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCj1TKtjujUBbXul01URMq4uYl8qcc2zE',
    appId: '1:169272546770:android:0b0fa9ee116b4d43f3a40b',
    messagingSenderId: '169272546770',
    projectId: 'alumniconnect-722b6',
    databaseURL: 'https://alumniconnect-722b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alumniconnect-722b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf8RZeUu1kwFA0jQXSxVpV-ZM3KOr6-6c',
    appId: '1:169272546770:ios:f8155b113e9ad5cdf3a40b',
    messagingSenderId: '169272546770',
    projectId: 'alumniconnect-722b6',
    databaseURL: 'https://alumniconnect-722b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alumniconnect-722b6.firebasestorage.app',
    iosClientId: '169272546770-3jp62rr6u1f8dc9i4i9haacck9eula0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.alumniconnect',
  );
}
