# Career GPS Engine Core Constants

# Readiness Score Weightages (must sum to 1.0)
WEIGHT_SKILL = 0.40
WEIGHT_PROJECT = 0.20
WEIGHT_EXPERIENCE = 0.15
WEIGHT_EDUCATION = 0.10
WEIGHT_CERTIFICATION = 0.05
WEIGHT_INTEREST = 0.10

# Skill Level Definition
MIN_SKILL_LEVEL = 0
MAX_SKILL_LEVEL = 5

# Priority weights
PRIORITY_WEIGHT_IMPORTANCE = 1.0
PRIORITY_WEIGHT_GAP = 1.5
PRIORITY_WEIGHT_DEPENDENCY = 1.2
PRIORITY_WEIGHT_TIMELINE = 0.8
